version: 0.2

phases:
  build:
    commands:
      - npm ci && npm install && npx prisma migrate deploy && npm run build # clean install (npm ci) and build (npm run build)

artifacts:
  files:
    - '**/*'
